/*
 * Performance Metrics Name Space Map
 * Built by pmgenmap.sh from the file
 * pmnsmap.spec
 * on Sun 31 Jan 2021 02:19:11 AM EET
 *
 * Do not edit this file!
 */

const char *pmclient_init[] = {
#define NUMCPU	0
	"hinv.ncpu",
#define RELEASE	1
	"kernel.uname.release",
#define VERSION	2
	"kernel.uname.version",
#define SYSNAME	3
	"kernel.uname.sysname",
#define MACHINE	4
	"kernel.uname.machine",
#define DISTRO	5
	"kernel.uname.distro",


};


const char *pmclient_sample[] = {
#define LOADAV	0
	"kernel.all.load",
#define CPU_USR	1
	"kernel.percpu.cpu.user",
#define CPU_SYS	2
	"kernel.percpu.cpu.sys",
#define FREEMEM	3
	"mem.freemem",
#define DKIOPS	4
	"disk.all.total",
#define MEMRSS	5
	"proc.psinfo.rss",

};

